[project]
name = "buildmecar-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "buildhat>=0.9.0",
    "flask>=3.1.2",
    "greenlet>=3.3.0",
]

[project.scripts]
test_motors = "buildmecar.test_motors:main"